In [1]:
#Importación de librerias
import numpy as np
import pandas as pd
import math
from matplotlib import pyplot as plt
import plotly.express as px

from Generico import Graficos

#Imprimir los graficos en el notebook
%matplotlib inline

In [2]:
#Variables generales
ruta_model = "../Model/"
ruta_df = "../Datasets/"
semilla = 111

## 3. Análisis Exploratorio

### 3.1. Interpolation Method

* ADASYN

In [3]:
df_IM_A = pd.read_csv('{}Interpolation_Method_ADASYN_Train.csv'.format(ruta_df))

In [4]:
df_IM_A.describe()

,FLAG,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,2014/1/17,...,Quartile_1,Quartile_3,Norm,IQR,Percentile_15,Percentile_65,Percentile_85,Median_Absolute_Deviation,kstat,KStatvar
count,48861.000000,48861.000000,48861.000000,48861.000000,48861.000000,48861.000000,48861.000000,48861.000000,48861.000000,48861.000000,...,48861.000000,48861.000000,48861.000000,48861.000000,48861.000000,48861.000000,48861.000000,48861.000000,4.886100e+04,4.886100e+04
mean,0.443646,5.032446,5.257353,4.975634,5.173563,5.440386,5.250598,5.228979,5.114625,4.841339,...,3.348696,12.586911,374.608378,9.238215,2.251015,8.609534,16.736187,2.780675,1.604206e+03,1.054676e+09
std,0.496819,26.604964,33.584573,28.855463,26.783904,48.359029,26.202735,28.037944,28.681868,26.001408,...,13.580061,57.430000,1610.053161,50.990715,9.956283,34.800131,75.532754,14.090451,7.898636e+04,1.920397e+11
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,2.089548,83.245375,1.520000,0.000000,0.000000,3.502000,0.000000,3.065230e+00,2.532685e-02
50%,0.000000,0.030000,0.000000,0.005797,0.049047,0.091971,0.036677,0.039527,0.009241,0.010000,...,0.092314,6.356067,191.356955,4.187500,0.000000,3.694500,8.540000,0.925000,1.309823e+01,3.702112e-01
75%,1.000000,5.548725,5.218598,5.140533,5.429124,5.390000,5.410769,5.530761,5.407375,5.290000,...,3.821558,11.805337,340.104285,8.210000,2.217500,9.040000,15.091500,2.690271,4.093567e+01,3.386052e+00
max,1.000000,3318.000000,3966.000000,4392.000000,3414.000000,6078.461043,2802.000000,3960.000000,3654.000000,3306.000000,...,762.600000,5239.500000,108152.131886,5239.500000,596.320000,2270.140000,5922.300000,1380.000000,1.128926e+07,4.223538e+13

In [5]:
from ipywidgets import interact, interact_manual
df_IM_ADASYN_grafico = Graficos(df_IM_A.drop(df_IM_A.filter(like='/', axis=1).columns, axis=1).drop(columns='Three_Sigma_Rule'))

In [6]:
interact_manual(
    df_IM_ADASYN_grafico.Correlacion
    , method = ['pearson', 'kendall', 'spearman']
    , TipoGrafico = np.arange(3)
)

interactive(children=(Dropdown(description='method', options=('pearson', 'kendall', 'spearman'), value='pearso…

In [7]:
interact_manual(
    df_IM_ADASYN_grafico.BoxPlot
    , Caracteristica = df_IM_A.loc[:, 'Sum':]
    , limite = ['Ninguno', 'FLAG = 0', 'FLAG = 1', 'General']
)

interactive(children=(Dropdown(description='Caracteristica', options=('Sum', 'Mean', 'Median', 'Standard_Dev',…

In [8]:
"""
obs
 análisis a filtros 
"""
_filtro = 18.394252356855553
print(f'''
Sin filtro: 
    Filas: {df_IM_A.shape[0]}
    Sin Fraude: {df_IM_A.FLAG.value_counts()[0]}
    Con Fraude: {df_IM_A.FLAG.value_counts()[1]}
Con Filtro:
    Filas: {df_IM_A.query("Mean < @_filtro").shape[0]}
    Sin Fraude: {df_IM_A.query("Mean < @_filtro").FLAG.value_counts()[0]}
    Con Fraude: {df_IM_A.query("Mean < @_filtro").FLAG.value_counts()[1]}
''')

Sin filtro:
    Filas: 48861
    Sin Fraude: 27184
    Con Fraude: 21677
Con Filtro:
    Filas: 45632
    Sin Fraude: 26264
    Con Fraude: 19368

In [9]:
#_temp = df_IM_A.query("Mean < @_filtro")
_temp = df_IM_A
_temp_grafico = Graficos(_temp.drop(df_IM_A.filter(like='/', axis=1).columns, axis=1).drop(columns='Three_Sigma_Rule'))
_sel_col = _temp_grafico.calcular_correlacion('FLAG', 5, "alta corr") # "alta corr", "baja corr"
_sel_col.append("FLAG")
_sel_col

['Mean', 'Sum', 'Percentile_85', 'Norm', 'Median_Absolute_Deviation', 'FLAG']

In [10]:
#Exportación del dataset modificado 2 
df_IM_A[_sel_col].to_csv('{}Interpolation_Method_ADASYN_Train_Modificado.csv'.format(ruta_df), index=False)

* SMOTE

In [11]:
df_IM_s = pd.read_csv('{}Interpolation_Method_SMOTE_Train.csv'.format(ruta_df))

In [12]:
df_IM_s.describe()

,FLAG,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,2014/1/17,...,Quartile_1,Quartile_3,Norm,IQR,Percentile_15,Percentile_65,Percentile_85,Median_Absolute_Deviation,kstat,KStatvar
count,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,...,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,4.893100e+04,4.893100e+04
mean,0.444442,6.354165,7.121500,6.510913,6.636135,7.269206,6.692252,6.705905,6.581054,6.195870,...,3.953679,16.431987,484.492849,12.478308,2.663302,10.658140,22.059204,3.578518,4.234730e+03,1.315216e+09
std,0.496909,48.297328,63.196567,57.992391,50.858546,76.356062,45.233780,53.251758,51.948736,47.054330,...,18.125921,95.603249,2610.820709,86.546462,13.105286,54.589785,127.265256,24.808455,1.195598e+05,1.928688e+11
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,2.184653,84.791421,1.577486,0.000000,0.000000,3.570750,0.000000,3.068097e+00,2.434495e-02
50%,0.000000,0.005007,0.000000,0.000000,0.020000,0.050000,0.009709,0.013389,0.000000,0.000000,...,0.045256,6.560000,195.532488,4.233750,0.000000,3.704500,8.731000,0.900000,1.331853e+01,3.757028e-01
75%,1.000000,5.634648,5.309149,5.299263,5.632351,5.560624,5.587143,5.680000,5.559916,5.459283,...,3.967987,12.187500,351.168070,8.444325,2.360000,9.170000,15.550000,2.658630,4.327281e+01,3.716754e+00
max,1.000000,3318.000000,3966.000000,4392.000000,3414.000000,6078.461043,2802.000000,3960.000000,3654.000000,3306.000000,...,762.600000,5239.500000,108152.131886,5239.500000,596.320000,2270.140000,5922.300000,1380.000000,1.128926e+07,4.223538e+13

In [13]:
from ipywidgets import interact, interact_manual
df_IM_SMOTE_grafico = Graficos(df_IM_s.drop(df_IM_A.filter(like='/', axis=1).columns, axis=1).drop(columns='Three_Sigma_Rule'))

In [14]:
interact_manual(
    df_IM_SMOTE_grafico.Correlacion
    , method = ['pearson', 'kendall', 'spearman']
    , TipoGrafico = np.arange(3)
)

interactive(children=(Dropdown(description='method', options=('pearson', 'kendall', 'spearman'), value='pearso…

In [15]:
interact_manual(
    df_IM_SMOTE_grafico.BoxPlot
    , Caracteristica = df_IM_s.loc[:, 'Sum':]
    , limite = ['Ninguno', 'FLAG = 0', 'FLAG = 1', 'General']
)

interactive(children=(Dropdown(description='Caracteristica', options=('Sum', 'Mean', 'Median', 'Standard_Dev',…

In [16]:
"""
obs
"""
_filtro = 19.0331634701634
print(f'''
Sin filtro: 
    Filas: {df_IM_s.shape[0]}
    Sin Fraude: {df_IM_s.FLAG.value_counts()[0]}
    Con Fraude: {df_IM_s.FLAG.value_counts()[1]}
Con Filtro:
    Filas: {df_IM_s.query("Mean < @_filtro").shape[0]}
    Sin Fraude: {df_IM_s.query("Mean < @_filtro").FLAG.value_counts()[0]}
    Con Fraude: {df_IM_s.query("Mean < @_filtro").FLAG.value_counts()[1]}
''')

Sin filtro:
    Filas: 48931
    Sin Fraude: 27184
    Con Fraude: 21747
Con Filtro:
    Filas: 45462
    Sin Fraude: 26323
    Con Fraude: 19139

In [17]:
#_temp = df_IM_s.query("Mean < @_filtro")
_temp = df_IM_s
_temp_grafico = Graficos(_temp.drop(df_IM_s.filter(like='/', axis=1).columns, axis=1).drop(columns='Three_Sigma_Rule'))
_sel_col = _temp_grafico.calcular_correlacion('FLAG', 5, "alta corr") # "alta corr", "baja corr"
_sel_col.append("FLAG")
_sel_col

['Mean', 'Sum', 'Norm', 'Percentile_85', 'Percentile_65', 'FLAG']

In [18]:
#Exportación del dataset modificado
df_IM_s[_sel_col].to_csv('{}Interpolation_Method_SMOTE_Train_Modificado.csv'.format(ruta_df), index=False)

### 3.2. Regresión Lineal

* ADASYN

In [19]:
df_LR_A = pd.read_csv('{}Linear_Regression_ADASYN_Train.csv'.format(ruta_df))

In [20]:
df_LR_A.describe()

,FLAG,0,1,2,3,4,5,6,7,8,...,Quartile_1,Quartile_3,Norm,IQR,Percentile_15,Percentile_65,Percentile_85,Median_Absolute_Deviation,kstat,KStatvar
count,48685.000000,48685.000000,48685.000000,48685.000000,48685.000000,48685.000000,48685.000000,48685.000000,48685.000000,48685.000000,...,48685.000000,48685.000000,48685.000000,48685.000000,48685.000000,48685.000000,48685.000000,48685.000000,4.868500e+04,4.868500e+04
mean,0.441635,8.306115,8.480203,8.136106,8.331022,11.482312,8.439760,8.541735,8.333232,7.825019,...,6.272865,15.088466,439.572708,8.815601,4.886264,12.446274,18.765328,3.595881,1.245211e+03,2.589006e+08
std,0.496587,32.134915,41.185065,36.860250,33.040334,61.573382,30.973837,35.507766,35.168258,30.920205,...,16.158067,58.178830,1600.578363,46.774309,12.623686,41.075608,75.688443,16.953133,4.769100e+04,3.120341e+10
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.572127,0.000000,0.000000,0.000000,0.000000,0.000000,3.165663e-04,1.002045e-07
25%,0.000000,2.044947,1.907507,2.250000,2.628913,0.600000,2.370000,1.757389,1.908354,2.355096,...,1.184447,5.727910,166.167183,2.605000,0.515671,4.784500,7.030500,1.123426,5.335900e+00,6.480939e-02
50%,0.000000,6.270000,5.724534,5.830000,6.315334,6.001659,6.062481,5.803087,5.790000,5.969098,...,4.620802,8.599478,251.120239,4.177371,3.297510,7.717861,10.145645,1.823031,1.192209e+01,2.797362e-01
75%,1.000000,8.183843,7.543697,7.697175,7.680000,13.091408,7.994695,8.510166,8.230304,7.439300,...,7.306601,13.051780,385.660133,7.106256,6.315309,11.352181,15.761000,2.895000,3.102379e+01,2.930017e+00
max,1.000000,3318.000000,3966.000000,4392.000000,3414.000000,6081.654293,2802.000000,3960.000000,3654.000000,3306.000000,...,801.300000,5263.500000,111190.344948,4657.852799,685.000000,2315.144091,5940.300000,1332.000000,5.744161e+06,6.098180e+12

In [21]:
from ipywidgets import interact, interact_manual
df_LR_A_grafico = Graficos(df_LR_A.drop(columns=df_LR_A.columns[df_LR_A.columns.str.match(r'^\d+$')]).drop(columns='Three_Sigma_Rule'))

In [22]:
interact_manual(
    df_LR_A_grafico.Correlacion
    , method = ['pearson', 'kendall', 'spearman']
    , TipoGrafico = np.arange(3)
)

interactive(children=(Dropdown(description='method', options=('pearson', 'kendall', 'spearman'), value='pearso…

In [23]:
interact_manual(
    df_IM_SMOTE_grafico.BoxPlot
    , Caracteristica = df_LR_A.loc[:, 'Sum':]
    , limite = ['Ninguno', 'FLAG = 0', 'FLAG = 1', 'General']
)

interactive(children=(Dropdown(description='Caracteristica', options=('Sum', 'Mean', 'Median', 'Standard_Dev',…

In [24]:
"""
obs
"""
_filtro = 19.0331634701634
print(f'''
Sin filtro: 
    Filas: {df_LR_A.shape[0]}
    Sin Fraude: {df_LR_A.FLAG.value_counts()[0]}
    Con Fraude: {df_LR_A.FLAG.value_counts()[1]}
Con Filtro:
    Filas: {df_LR_A.query("Mean < @_filtro").shape[0]}
    Sin Fraude: {df_LR_A.query("Mean < @_filtro").FLAG.value_counts()[0]}
    Con Fraude: {df_LR_A.query("Mean < @_filtro").FLAG.value_counts()[1]}
''')

Sin filtro:
    Filas: 48685
    Sin Fraude: 27184
    Con Fraude: 21501
Con Filtro:
    Filas: 44826
    Sin Fraude: 26095
    Con Fraude: 18731

In [25]:
#_temp = df_LR_A.query("Mean < @_filtro")
_temp = df_LR_A
_temp_grafico = Graficos(_temp.drop(df_LR_A.filter(regex='[0-9]', axis=1).columns, axis=1).drop(columns='Three_Sigma_Rule'))
_sel_col = _temp_grafico.calcular_correlacion('FLAG', 5, "alta corr") # "alta corr", "baja corr"
_sel_col.append("FLAG")
_sel_col

['Sum', 'Mean', 'Median', 'Norm', 'Median_Absolute_Deviation', 'FLAG']

In [26]:
#Exportación del dataset modificado 2 
df_LR_A[_sel_col].to_csv('{}Linear_Regression_ADASYN_Train_Modificado.csv'.format(ruta_df), index=False)

* SMOTE

In [27]:
df_LR_s = pd.read_csv('{}Linear_Regression_SMOTE_Train.csv'.format(ruta_df))

In [28]:
df_LR_s.describe()

,FLAG,0,1,2,3,4,5,6,7,8,...,Quartile_1,Quartile_3,Norm,IQR,Percentile_15,Percentile_65,Percentile_85,Median_Absolute_Deviation,kstat,KStatvar
count,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,...,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,48931.000000,4.893100e+04,4.893100e+04
mean,0.444442,9.396682,10.206922,9.453727,9.474180,14.201297,9.911674,10.071532,9.693098,9.016267,...,7.180981,19.036827,549.496059,11.855846,5.528136,15.152114,23.895966,4.651092,3.478531e+03,3.931844e+08
std,0.496909,46.989004,62.505611,57.114181,48.709726,99.709314,46.310079,55.034598,52.370321,46.684835,...,22.712880,99.996289,2647.817179,83.229628,17.127985,65.014884,128.612538,28.075135,9.203727e+04,3.249371e+10
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.572127,0.000000,0.000000,0.000000,0.000000,0.000000,3.165663e-04,1.002045e-07
25%,0.000000,2.080000,1.930194,2.276850,2.690000,0.570000,2.435273,1.803215,1.970000,2.386296,...,1.300518,5.827602,169.001003,2.567500,0.591394,4.884500,7.105461,1.113888,5.132125e+00,6.104022e-02
50%,0.000000,6.342486,5.803462,5.872806,6.380000,5.987158,6.075848,5.904096,5.910000,6.041567,...,4.715041,8.725697,255.328015,4.183896,3.425421,7.808672,10.310000,1.825495,1.194431e+01,2.814619e-01
75%,1.000000,8.184124,7.590704,7.719738,7.712651,13.143509,8.110000,8.610920,8.308131,7.446055,...,7.470253,13.400066,397.060791,7.289821,6.557378,11.663500,16.280750,2.985000,3.279072e+01,3.240583e+00
max,1.000000,3318.000000,3966.000000,4392.000000,3414.000000,6081.654293,2802.000000,3960.000000,3654.000000,3306.000000,...,801.300000,5263.500000,111190.344948,4657.852799,685.000000,2315.144091,5940.300000,1332.000000,5.744161e+06,6.098180e+12

In [29]:
from ipywidgets import interact, interact_manual
df_LR_SMOTE_grafico = Graficos(df_LR_s.drop(columns=df_LR_s.columns[df_LR_s.columns.str.match(r'^\d+$')]).drop(columns='Three_Sigma_Rule'))

In [30]:
df_LR_s.drop(columns=df_LR_s.columns[df_LR_s.columns.str.match(r'^\d+$')]).drop(columns='Three_Sigma_Rule')

,FLAG,Sum,Mean,Median,Standard_Dev,Variance,Peak_to_Peak,Kurtosis,Quartile_1,Quartile_3,Norm,IQR,Percentile_15,Percentile_65,Percentile_85,Median_Absolute_Deviation,kstat,KStatvar
0,0,6706.143123,6.485632,6.665959,3.501832,12.262828,19.107058,0.930762,4.359823,8.334824,236.983280,3.975002,1.880000,7.605359,9.679867,1.874588,12.262828,0.427186
1,0,8076.437864,7.810868,7.464701,1.617485,2.616257,12.816218,1.212460,6.777485,8.517500,256.488959,1.740015,6.395864,8.135222,9.260500,0.862766,2.616257,0.021315
2,0,12993.749375,12.566489,11.407859,6.571959,43.190645,45.395579,1.399483,7.372500,16.947500,455.962434,9.575000,5.738500,14.493500,19.410500,4.670541,43.190645,6.147334
3,0,7889.847758,7.630414,6.170000,5.337780,28.491895,19.123062,-0.398579,3.857500,10.525000,299.390932,6.667500,2.810000,8.799000,14.360000,2.920000,28.491895,1.259404
4,0,5834.787694,5.642928,5.980000,4.594063,21.105417,15.184556,-1.077841,0.000000,9.092500,233.938419,9.092500,0.000000,7.934500,10.520500,4.090000,21.105417,0.397579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48926,1,6300.762660,6.093581,5.934265,2.455724,6.061587,12.212950,-0.158958,4.236967,7.735386,211.305658,3.498419,3.414381,6.891239,8.568304,1.740276,6.061587,0.066151
48927,1,5620.394554,5.435585,5.282528,1.949302,3.853534,10.218827,0.606623,4.276249,6.545086,185.797823,2.268837,3.754775,5.934819,7.280352,1.133662,3.853534,0.039262
48928,1,7190.583097,6.954142,7.022442,2.450931,6.008938,14.235234,0.448055,5.329381,8.208644,237.089960,2.879263,4.148839,7.662643,9.186438,1.359963,6.008938,0.085861
48929,1,14776.832423,14.290940,12.909263,11.150403,126.313109,98.752826,4.157943,2.586552,23.114246,583.992481,20.527694,1.112530,19.608137,26.693568,10.115850,126.313109,122.325460
48930,1,6376.477148,6.166806,6.597240,2.977872,8.874453,13.699646,-0.119762,4.681386,7.901002,220.198539,3.219616,2.358371,7.377811,8.746278,1.507133,8.874453,0.145106

In [31]:
interact_manual(
    df_LR_SMOTE_grafico.Correlacion
    , method = ['pearson', 'kendall', 'spearman']
    , TipoGrafico = np.arange(3)
)

interactive(children=(Dropdown(description='method', options=('pearson', 'kendall', 'spearman'), value='pearso…

In [32]:
interact_manual(
    df_LR_SMOTE_grafico.BoxPlot
    , Caracteristica = df_LR_s.loc[:, 'Sum':]
    , limite = ['Ninguno', 'FLAG = 0', 'FLAG = 1', 'General']
)

interactive(children=(Dropdown(description='Caracteristica', options=('Sum', 'Mean', 'Median', 'Standard_Dev',…

In [33]:
"""
obs
"""
_filtro = 20.799652309382274
print(f'''
Sin filtro: 
    Filas: {df_LR_s.shape[0]}
    Sin Fraude: {df_LR_s.FLAG.value_counts()[0]}
    Con Fraude: {df_LR_s.FLAG.value_counts()[1]}
Con Filtro:
    Filas: {df_LR_s.query("Mean < @_filtro").shape[0]}
    Sin Fraude: {df_LR_s.query("Mean < @_filtro").FLAG.value_counts()[0]}
    Con Fraude: {df_LR_s.query("Mean < @_filtro").FLAG.value_counts()[1]}
''')

Sin filtro:
    Filas: 48931
    Sin Fraude: 27184
    Con Fraude: 21747
Con Filtro:
    Filas: 45144
    Sin Fraude: 26296
    Con Fraude: 18848

In [34]:
#_temp = df_LR_s.query("Mean < @_filtro")
_temp = df_LR_s
_temp_grafico = Graficos(_temp.drop(df_LR_s.filter(regex='[0-9]', axis=1).columns, axis=1).drop(columns='Three_Sigma_Rule'))
_sel_col = _temp_grafico.calcular_correlacion('FLAG', 7, "alta corr") # "alta corr", "baja corr"
_sel_col.append("FLAG")
_sel_col

['Mean',
 'Sum',
 'Median',
 'Norm',
 'Median_Absolute_Deviation',
 'Standard_Dev',
 'IQR',
 'FLAG']

In [35]:
#Exportación del dataset modificado 2 
df_LR_s[_sel_col].to_csv('{}Linear_Regression_SMOTE_Train_Modificado.csv'.format(ruta_df), index=False)